apiVersion: v2
name: hermes-agent
description: Cloud-native Helm chart for Nous Research's Hermes Agent
type: application
version: 0.2.0
appVersion: v2026.8.3
kubeVersion: ">=1.25.0-0"
keywords:
  - hermes
  - ai
  - agent
  - llm
  - gateway
  - acp
  - mcp
home: https://hermes-agent.nousresearch.com
icon: https://raw.githubusercontent.com/NousResearch/hermes-agent/main/landingpage/icon-192.png
sources:
  - https://github.com/nousresearch/hermes-agent
  - https://github.com/MichaelSp/hermes-agent-helm-chart
maintainers:
  - name: Michael Wenk
    url: https://github.com/mwenkdev
