name: PR Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Helm Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0

      - name: Install Helm
        uses: azure/setup-helm@v5.0.1
        with:
          version: "4.2.3"

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.1.2 --verify=false

      - name: Lint chart
        run: helm lint .

      - name: Run unit tests
        run: helm unittest .
